spring:
  application:
    name: spring-crac
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  # add spring data jpa to connect with mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring-crac
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      continue-on-error: true
      platform: mysql
      mode: always

  threads:
    virtual:
      enabled: true